language: python
python:
  - "3.6"
  
# command to install dependencies
#install:
#  - pip install -r requirements.txt

before_script:
- git clone https://github.com/zhajio1988/uvm_candy_lover.git
- cd uvm_candy_lover/bin
- git clone https://github.com/zhajio1988/YASA.git
- cd ../
- touch bin/vcs
- chmod +x bin/vcs
- export PATH="./bin":$PATH
- source bin/bootenv.csh

# command to run tests
script:
  -  alias YASAsim="python3 $PRJ_HOME/bin/YASA/yasaTop.py"; YASAsim -doc
  -  python3 $PRJ_HOME/bin/YASA/yasaTop.py -h
  -  YASAsim -doc
  -  YASAsim -show test
  -  YASAsim -show build
  -  YASAsim -show group

after_script:
- rm -f bin/vcs
